============================= test session starts =============================
platform win32 -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0 -- C:\Users\JM\AppData\Local\anaconda3\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\RiskSampler
plugins: anyio-3.5.0
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
_______________ ERROR collecting tests/unit/test_risksampler.py _______________
ImportError while importing test module 'C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\RiskSampler\tests\unit\test_risksampler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\JM\AppData\Local\anaconda3\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
C:\Users\JM\AppData\Local\anaconda3\Lib\site-packages\_pytest\pathlib.py:565: in import_path
    importlib.import_module(module_name)
C:\Users\JM\AppData\Local\anaconda3\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
C:\Users\JM\AppData\Local\anaconda3\Lib\site-packages\_pytest\assertion\rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests\unit\test_risksampler.py:5: in <module>
    from risk_sampler.core import RiskSampler
E   ModuleNotFoundError: No module named 'risk_sampler'
============================== warnings summary ===============================
..\..\..\..\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61
  C:\Users\JM\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
    from pandas.core import (

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
ERROR tests/unit/test_risksampler.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.72s =========================
